### ISSUE TITLE
Can't set the style

### ISSUE THREAD

**Issue by Maniumn** [dreambo8563/vue-simple-drawer#38]
Here is my empty project with simple drawer installed and with style background setted to yellow [git project](https://github.com/Maniumn/vue-simple-drawer).
The problem is, the background stay #333333. What do I do wrong?
The toggle button is in About.vue
![style](https://i.imgur.com/9889U2h.png)

**Comment by dreambo8563** [comment]
sorry, wrong description in docs, should import the override scss after importing the component,

```js
import Drawer from "vue-simple-drawer";
import "@/assets/scss/demo.scss";
```
